trigger:
- 1.0.x

pool:
  name: Default

jobs:
- job: CI
  steps:
  - script: docker build -t devopsyo/payoneer-counter .
    displayName: 'Push Docker Image'
- job: CD
  dependsOn: CI
  steps:
  - script: docker image pull devopsyo/payoneer-counter
    displayName: 'Pull Docker Image'
