pool:
  name: Default

jobs:
- job: CI
  steps:
  - script: docker build -t devopsyo/payoneer-counter .
    displayName: 'Build Docker Image'
  - script: docker login -u $(DOCKERHUB_USER) -p $(DOCKERHUB_PWD)
    displayName: 'Login Docker Image'
  - script: docker image push devopsyo/payoneer-counter
    displayName: 'Push Docker Image'
- job: CD
  dependsOn: CI
  steps:
  - script: docker image pull devopsyo/payoneer-counter
    displayName: 'Pull Docker Image'
