variables:
- group: payoneer-counter-variables-group

parameters:
- name: tag
  displayName: Tag
  type: string
  default: 1.0.x

pool:
  name: Default


jobs:
- job: CD
  steps:
  - script: docker image pull $(DOCKERHUB_USER)/$(IMAGE):${{ parameters.tag }}
    displayName: 'Pull Docker Image'
  - script: |
      containers=$(docker ps -q --filter "status=running" --filter "expose=$(EXTERNAL_PORT)") ; \
      if [ -n "$containers" ]; then \
        docker rm -f $containers ; \
      fi ; \ 
    displayName: 'Remove running container'
  - script: docker run --restart=always -d -v log:/app/log -p $(EXTERNAL_PORT):$(INTERNAL_PORT) $(DOCKERHUB_USER)/$(IMAGE):${{ parameters.tag }}
    displayName: 'Start Container'
